[package]
name = "matrixable"
version = "0.1.0"
edition = "2021"
authors = ["tcheufa"]
description = "Traits for extending matrix-like structures capabilities."
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }

